apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  config.yaml: |
    endpoints: {{ .Values.endpoints | toYaml | nindent 6 }}
